### ISSUE TITLE
Latest release breaks colors on a ton of websites

### ISSUE THREAD

**Issue by Ten0** [mozilla/contain-facebook#867]
Facebook Container auto-updated to the latest release today, and it immediately broke color on a ton of websites, e.g. google, github...

# Expected behavior
![image](https://user-images.githubusercontent.com/9094255/189150838-b20b090b-6ed1-4b70-95dd-78daf0c27eb0.png)

# Actual behavior
![image](https://user-images.githubusercontent.com/9094255/189150852-798cb6e9-9a4b-48bf-bcdc-3fd5ef2ef532.png)

# Explanation

The issue appears to come from a style sheet the extension injects on every page:
`moz-extension://0e0da617-2f41-4dfb-bea7-9255dd283cc9/content_script.css`

which notably contains:
```css
body {
    --blue60: #0060df;
    --blue70: #003eaa;
    --primaryText: #15141A;
    --secondaryText: #5B5B66;
    --grey20: #ededf0;
	--light-gray: #F0F0F4;
	--white: #ffffff;
    --transition: all .15s cubic-bezier(.07,.95,0,1);
    --borders: 1px solid #ededf0;
	font-size: 13px;
	font-weight: 400;
	color: #15141A;
    font-family: "SF Pro Text", 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
}
```

I don't see why this extension should inject any style sheet anywhere whatsoever.
